#! /bin/sh
#     ___    ____  __    ___   _________
#    /   |  / _  |/ /   / / | / /__  __/           Source Code Static Analyzer
#   / /| | / / / / /   / /  |/ /  / /                   AdLint - Advanced Lint
#  / __  |/ /_/ / /___/ / /|  /  / /
# /_/  |_|_____/_____/_/_/ |_/  /_/   Copyright (C) 2010-2014, OGIS-RI Co.,Ltd.
#
# Shell script generated by adlintize 3.2.14 at 2014-06-15 11:32:50 -0300

adlint -v -t adlint_traits.yml -o . -p 1 -l adlint_files.txt
